---
- name: Python 3
  apt:
    state: present
    pkg:
      - python3
      - pypy3
      - python3-doc     # 37.2 mb
      - pypy3-doc # 5mb

- name: ipython
  apt:
    state: present
    install_recommends: false # it's like 500MB with recommends vs 14MB without
    pkg:
      - ipython3

- name: register docs
  block:
    - ansible.utils.update_fact:
        updates:
          - path: "lang_docs['Python 3']"
            value:
              name: Python 3 Documentation
              id: py3
              path: /usr/share/doc/python3-doc/html
              index: index.html
          - path: "lang_docs['PyPy 3']"
            value:
              name: PyPy3 Documentation
              id: pypy3
              path: /usr/share/doc/pypy3-doc/html
              index: index.html
      register: updated
    - set_fact:
        lang_docs: "{{ updated.lang_docs }}"
